trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 1

- task: NodeTool@0
  inputs:
    versionSpec: '22.5.1'
    checkLatest: true

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build the app'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
